### ISSUE TITLE
Systems Biology Ontology URIs

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/SBOL-specification#388] opened 2020-08-24 23:32 UTC
The SBOL 3 specification lists two different prefixes for the Systems Biology Ontology. In Section 6.4 Table 2, on page 18, the prefix is shown as `https://identifiers.org/SBO:`. In other sections/tables the prefix is listed as `http://identifiers.org/biomodels.sbo/SBO:`. See, for example, Section 6.4 Table 10, on page 29, and Section 6.4 Table 11, on page 30. Both of these prefixes appear to work, and link on to `https://www.ebi.ac.uk/sbo/main/SBO:0000251`, for example.

Should the specification use a single prefix for the Systems Biology Ontology?

What is the canonical URI prefix for the Systems Biology Ontology? I couldn't find a definitive statement about the proper URI prefix in my (limited) surfing.

**Comment by jakebeal** [comment] 2020-08-24 23:42
Is this a duplicate of #366?

**Comment by tcmitchell** [comment] 2020-08-25 13:23
This might be a duplicate of #366, I'm not sure. This is more about internal inconsistency in the document, and that one seems to be more about updating to the new scheme across all of the identifiers.org URIs. It may be the case that both can be closed by the same fix, depending on how #366 gets resolved.

I'll leave it to others to decide whether this is a duplicate.

**Comment by goksel** [comment] 2020-08-25 23:23
Yes, this is the same issue as #366. I suggest closing this one.

**Closed** 2020-08-26 02:06 UTC
Labels: duplicate
