### ISSUE TITLE
Define precise meaning of "locally unique" for sbol-10205

### ISSUE THREAD

**Issue by zgzn** [SynBioDex/SBOL-specification#42] opened 2016-02-21 23:06 UTC
This best-practice rule requires the display ID of an identified object to be locally unique. The local uniqueness needs to be defined with a scope. For example, we can require unique display ID for each top-level object that exists in an SBOL document.

**Comment by bbartley** [comment] 2016-03-03 01:24
The meaning of locally unique is indeed entirely ambiguous to me.  Can you explain what the intent of this rule is, and whom the idea originated with?  If the scope of "locally unique" is not clearly defined in the spec, then this validation rule is meaningless.  I wouldn't mind removing the rule entirely without an SEP, as Chris advocated, if we can be certain that no one in the community is really invested in it.  However, until I'm certain of that, we must use an SEP to either 1) clarify the scope, or 2) remove the rule.

**Comment by cjmyers** [comment] 2016-03-03 03:23
This rule was introduced by me.  It is a hold over from SBOL 1.1, when I wanted displayIds to be unique within a document, in the SBML-style.  This, however, was converted into a best practice in SBOL 2.0, because it caused some problems in 1.1.  I’ve since realized that it really serves no purpose and is not really good practice at all, since it is very convenient to say give a Component the same displayId as a ComponentDefinition.

I do not believe an SEP is required to remove this rule because it is a best practice and not a validation rule, so removing it does not change the data model. It will effect no tool development efforts at all.

Chris

**Comment by jakebeal** [comment] 2016-03-03 14:21
If this doesn't resolve clearly before the Boston meeting, we should discuss in detail there and either edit directly in or SEP, as gets clarified and understood.

**Comment by jakebeal** [comment] 2016-03-15 14:39
This rule has been determined to be meaningless and will be deleted.

**Comment by graik** [comment] 2016-03-19 12:06
"Locally unique" was supposed to mean that the displayID could serve to uniquely identify a part within the context of a parts registry (or similar). So whoever creates a new part with a new displayID should make sure that there never will be another part with the same ID within the namespace that she/he has control over. This was supposed to facilitate communication about / location of genetic parts. I thought I am the author of this very fuzzy term :) but it seems that there was different interpretations from the start.

In semantic web terms, we assumed a SBOL resource to be identified like this:
<http://provider_partsregistry.org/somecollection>#<ID> 
and displayID was supposed to be identical to the RDF subject ID (the part after the #). 

Practically, there was by definition no way to enforce that. This touches URI creation and other things. I would argue this statement should not just be silently deleted but there needs to be some sort of SEP to discuss alternatives.

**Comment by jakebeal** [comment] 2016-03-19 12:28
That's a lot of assumptions about structure that cannot be justified.  The sense of the room at the meeting was that "locally" was completely ill-defined.

**Comment by graik** [comment] 2016-03-19 12:36
At some point before the meeting, someone raised the topic of how to compose URIs that can be resolved into actual SBOL documents. To me this, as well as the proposal to rename displayID, all look related. As Matt pointed out commenting on issue #54 , displayID was intended to serve as an (I would add human-readable) identifier [http://purl.org/dc/elements/1.1/identifier]. That's what "locally unique" referred to. 
I am fine with deleting a sentence that nobody understands and that cannot be validated but the nature of displayID and ressource location / identification is pretty crucial and needs to be clarified one way or another.

**Comment by jakebeal** [comment] 2016-03-19 12:54
Agreed.  Resolving this issue, however, is just about deleting the ill-defined sentence, and needs to be done for 2.0.1 in support of library development.

Can you please create a new clarification issue encapsulating your concerns and mark it for version 2.1.1 (linking to this issue and #54 for context)?

**Comment by cjmyers** [comment] 2016-03-19 16:05
Actually, this is already handled in the specification with the description of compliant SBOL objects in the best practices section.  The rule was deleted because the proper definition of it (following what you describe below) makes it redundant with respect to rules 10215 through 10219.  One of the goals of the validation rule edits was to make the rules independently checkable.  Namely, it should be possible to create an SBOL document for a checkable rule that violates only that rule.  Since locally unique defined as you express below would cause it to be covered by the other rules, this specific rule is no longer needed.

Hope this clarifies the situation.  The idea of displayId and its role has remained, just this now redundant rule is gone.

Chris

**Comment by graik** [comment] 2016-03-19 17:00
Thanks, Chris for pointing to these rules. These rules and section 11.2 of the specification indeed cover most of it. The description of displayId itself could be better though. I can see how it is difficult to distinguish the purpose of displayID from the name field. So this may be a minor issue to raise.

What we are missing altogether is reliable resolution of sbol URIs into actual documents. That's a larger issue and I sympathize with procrastination...

**Closed** 2016-04-29 12:09 UTC
Labels: Non-SEP change, ready-for-pull
